### ISSUE TITLE
Add svg support

### ISSUE THREAD

**Issue by theadam** [paldepind/snabbdom#4] opened 2015-06-08 03:25 UTC
Could this possibly be done with an extension?

**Comment by paldepind** [comment] 2015-06-08 06:31
Please expand a little on what you mean with svg support.

DOM element creation is handled by the core. And there is currently no way the core can create namespaced elements (easily fixable).

I've seen other virtual DOM libraries that automatically adds the correct namespace to svg elements.

**Comment by theadam** [comment] 2015-06-08 16:21
Yeah this is basically all i mean, being able to create namespaced elements.

Maybe a top level "namespace" or "ns" option to be put on a vnode's data.  Then the logic for creating this element (in core) would be use this to determine whether or not to use createElementNS or createElement.  At that point it should be simple to create hooks (in an extension) to automatically add the svg namespace to certain elements.  Would that work?

**Comment by paldepind** [comment] 2015-06-08 16:51
As far as I know only svg and MathML require namespaces.

Yes! That would work.

* If a `ns` property is supplied on a vnode's data it is created with `createElmentNs` (this is similar to virtual-dom).
* A `svg` module adds the correct namespace automatically to elements if their tag name is "svg".

**Comment by jails** [comment] 2015-06-14 12:03
> As far as I know only svg and MathML require namespaces.

When you are creating them through the DOM API you also need to apply it to all their children to make it works. 
https://jsfiddle.net/1byvqbqd/

**Comment by paldepind** [comment] 2015-06-14 16:52
@jails Thank you for the heads up. That is unfortunate.

**Comment by yelouafi** [comment] 2015-08-12 12:39
(Probably) a simpler idea is to have a separate factory function `svg`

```js
function svg(...args) {
  var vnode = h(...args);
  vnode.data.ns = 'http://www.w3.org/2000/svg'
  return vnode;
}
```

then use it like the `h` function

```js
var svg = require('snabbdom/svg')

var vnode = svg('svg', [ svg('circle', { ... }) ]);
```

The issue is inside the `{...}` i'm not that aware of SVG but i'm not sure if the `props` module would do it since all SVG examples i've seen so far relies on `setAttribute`. In snabbdom-jsx examples i used [an attributes module](https://github.com/yelouafi/snabbdom-jsx/blob/master/examples/hello-svg/snabbdom-modules/attributes.js) that's a mere copy of the `props` module

**Comment by paldepind** [comment] 2015-08-12 18:04
@yelouafi That is a _slendid_ idea! Such a simple solution for a problem that would otherwise require work inside the core (I have seen how other virtual DOM libraries handles this and it is an annoying complexity).

> In snabbdom-jsx examples i used an attributes module that's a mere copy of the props module

I'd love a PR with that module! :)

**Comment by yelouafi** [comment] 2015-08-12 20:42
>I'd love a PR with that module! :)

i'll be glad to do it. We just have a small issue to fix : how to deal with removed attributes. There are 2 ways to define it

1- an attribute is removed when it's not physically present in the object (either in the sens of the `in` operator or `hasOwnProperty` method)
2- an attribute is removed when it has some falsy value (null, undefined, false)

The 1st is more consistent but sometimes the 2nd option is more suitable especially in the case of Boolean attributes like `disabled` for example : a falsy value  means remove the attribute and not just set it to `false`. 

Or perhaps should we adopt a mixed approach : take the 1st option as the general rule, with exception for all known HTML boolean attributes where we opt for the 2nd solution.

**Comment by yelouafi** [comment] 2015-08-13 12:27
FYI i pushed the PR with the mixed approach (special handling for boolean attributes). i think i'd better to move the discussion on the PR

**Comment by zywind** [comment] 2015-11-13 16:35
Hi. Just wonder if SVG support has been implemented.  Virtual-dom supports svg in a similar fashion as described here.

**Comment by paldepind** [comment] 2015-11-18 08:07
@zywind It was never added to Snabbdom. I'll add in the helper function that @yelouafi suggested.

**Comment by zywind** [comment] 2015-11-18 14:55
Thanks a lot. Having SVG support would be tremendously useful.

**Comment by TylorS** [comment] 2015-11-18 19:15
It seems like this would be pretty easy, this is where its done in in *virtual-dom*https://github.com/Matt-Esch/virtual-dom/blob/master/virtual-hyperscript/svg.js

It seems as though it would just require a function which sets the namespace (for convenience), and then one could just use the attributes module as usual. Is there anything I'm missing?

**Comment by paldepind** [comment] 2015-11-19 21:03
I've now added [an svg helper to the repository](https://github.com/paldepind/snabbdom/blob/master/helpers/svg.js).

Usage is like this:

```js
var vnode = h('div', [
  svg({attrs: {width: 100, height: 100}}, [
    h('circle', {attrs: {cx: 50, cy: 50, r: 40, stroke: 'green', 'stroke-width': 4, fill: 'yellow'}})
  ])
]);
```

Instead of using `h('svg', ...` use `svg(...)`. The proper namespace will then be added to the svg element and all of its child elements.

To me this seems like a solution that is both simple in implementation and convenient in usage.

I'd like to hear opinions. This is not released yet.

**Comment by RangerMauve** [comment] 2015-11-19 21:09
:+1: It's the same thing that virtual-dom uses. Personally, I would have loved for `h` to just auto-detect svg tags, but I think that it'd be easy enough for someone to just make a wrapper for that use case if needed.

**Comment by TylorS** [comment] 2015-11-19 21:18
That looks like a simple solution to me! Do you think there will be any noticeable performance issues performing the recursion over the children like that?

Virtual-dom does is slightly differently (without the recursion), by using `svg('svg', {}, [ svg('circle', {}, [])])`. Where svg() adds the namespace to the supplied tagName, not all of its children. 

If the performance is negligible I like the proposed solution **much** more from a usability standpoint.

**Comment by yelouafi** [comment] 2015-11-19 22:52
@paldepind why the recursion in the children ? if we call `svg` in the children instead of `h` we wont need the recursion ? did i miss something ?
```javascript
var vnode = h('div', [
  svg({attrs: {width: 100, height: 100}}, [
    svg('circle', {attrs: {cx: 50, cy: 50, r: 40, stroke: 'green', 'stroke-width': 4, fill: 'yellow'}})
  ])
]);
```

**Comment by paldepind** [comment] 2015-11-20 10:51
> Do you think there will be any noticeable performance issues performing the recursion over the children like that?

No, not really. Recursion isn't expensive. Snabbdom and other virtual DOM libraries uses recursion to construct the DOM. As long as you don't hit the stack limit you should be fine.

> @paldepind why the recursion in the children ? if we call svg in the children instead of h we wont need the recursion ? did i miss something ?

That is only for convenience.

As far as I can tell there are three options:

* Users should use the `svg` helper on all `svg` elements–which gives the simplest implementation
* Users should only use the `svg` helper on the `svg` element itself. The current implementation.
* `h` detects `svg` elements and working with `svg` is seamless.

Instead of using recursion in the `svg` helper the core of Snabbdom could implement namespace inheriting. I'm aware that other virtual DOM libraries does that.

I'm currently thinking that going for user convenience as @RangerMauve suggests would be optimal. This also means that svg would automatically work with snabbdom-jsx as well.

**Comment by yelouafi** [comment] 2015-11-20 12:04
>I'm currently thinking that going for user convenience as @RangerMauve suggests would be optimal. This also means that svg would automatically work with snabbdom-jsx as well.

If you think the perf. costs aren't expensive then i don't see a particular problem; although my personal thinking is that using an explicit `svg` factory for each node makes the code intent more explicit, actually i think of `svg` like a partial application of `h`.

From the JSX point; snabbdom-jsx doesn't actually use the `h` function but constructs the vnodes directly; there is another factory `svg`; but given that we have to put a JSX pragma at the top of the source file we can't actually mix both html and svg content. the second approach seems to solve that issue : although the approach can be directly implemented inside snabbdom-jsx. Another solution is to use the `h` factory inside snabbdom-jsx and switch to `svg` whenever we encounter and svg tag.

**Comment by acstll** [comment] 2015-11-25 12:51
Though the current implementation works fine, I would go either with 1 or 3.

> (1) Users should use the svg helper on all svg elements–which gives the simplest implementation

*Good:* the most explicit approach and simplest implementation.
*Bad:* one extra thing to think about?

> (3) h detects svg elements and working with svg is seamless.

*Good:* it just works…
*Bad:* adding to core?

Hope this helps.

(Hi there, I'm new here. I'm planning to refactor a side project from `React` to `snabbdom` and it needs `svg` :smile:)

**Comment by paldepind** [comment] 2015-11-26 19:47
I don't really think that a separate `svg` helper makes the code more explicit in a way that really matters.

Consider this
```js
var vnode = h('div', [
  svg({attrs: {width: 100, height: 100}}, [
    svg('circle', {attrs: {cx: 50, cy: 50, r: 40, stroke: 'green', 'stroke-width': 4, fill: 'yellow'}})
  ])
]);
```
Versus this
```js
var vnode = h('div', [
  h('svg', {attrs: {width: 100, height: 100}}, [
    h('circle', {attrs: {cx: 50, cy: 50, r: 40, stroke: 'green', 'stroke-width': 4, fill: 'yellow'}})
  ])
]);
```

I think they're equally easy understand.

@acstll

> Bad: adding to core?

It can also be implemented inside `h` without touching core.

**Comment by paldepind** [comment] 2015-11-26 20:15
I've added svg support to `h` and released a new version with the feature.

I choose that approach because having svg "just work" seemed to be the simplest and most predictable approach with regards to the API. This also avoids having to reimplement stuff in the `svg` helper that is already is in the `h` helper.

Unless there is any objections I will close this issue.

**Comment by yelouafi** [comment] 2015-11-26 20:22
Ok for me. I think i'll do the same thing in snabbdom-jsx

**Comment by RangerMauve** [comment] 2015-11-26 21:17
Awesome! I think that solution will be easiest going forward. It'd be cool if virtual-dom did the same thing, but oh well.

**Comment by acstll** [comment] 2015-11-26 23:16
Loving it (both API and implementation).

**Comment by paldepind** [comment] 2015-11-27 14:38
I'm happy you like it :)

**Closed by paldepind** 2015-11-27 14:38 UTC
Labels: enhancement
